import type { Metadata } from "next";
import "./globals.css";
import { AuthBootstrap } from "@/components/auth-bootstrap";
import { AuthSessionSync } from "@/components/auth-session-sync";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AuthBootstrap />
        <AuthSessionSync />
        {children}
      </body>
    </html>
  );
}
