export enum ErrorDomain {
  AUTH = 'AUTH',
  PROVIDER_SYNC = 'PROVIDER_SYNC',
  AUDIO_PREVIEW = 'AUDIO_PREVIEW',
  ANONYMITY_REVEAL = 'ANONYMITY_REVEAL',
  COMPATIBILITY_SCORING = 'COMPATIBILITY_SCORING',
  MESSAGING_UNLOCK = 'MESSAGING_UNLOCK',
  EVENT_PARTICIPATION = 'EVENT_PARTICIPATION',
  STELLAR_PAYMENT = 'STELLAR_PAYMENT',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  VALIDATION = 'VALIDATION',
}

export enum ErrorCode {
  // Auth errors (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_002',
  AUTH_TOKEN_EXPIRED = 'AUTH_003',
  AUTH_TOKEN_INVALID = 'AUTH_004',
  AUTH_USER_NOT_FOUND = 'AUTH_005',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_006',
  AUTH_ONBOARDING_INCOMPLETE = 'AUTH_007',
  AUTH_ACCOUNT_LOCKED = 'AUTH_008',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_009',
  AUTH_PASSWORD_TOO_WEAK = 'AUTH_010',

  // Provider sync errors (PROVIDER_SYNC_xxx)
  PROVIDER_SYNC_CONNECTION_FAILED = 'PROVIDER_SYNC_001',
  PROVIDER_SYNC_API_RATE_LIMIT = 'PROVIDER_SYNC_002',
  PROVIDER_SYNC_INVALID_CREDENTIALS = 'PROVIDER_SYNC_003',
  PROVIDER_SYNC_SERVICE_UNAVAILABLE = 'PROVIDER_SYNC_004',
  PROVIDER_SYNC_DATA_MALFORMED = 'PROVIDER_SYNC_005',
  PROVIDER_SYNC_TIMEOUT = 'PROVIDER_SYNC_006',
  PROVIDER_SYNC_QUOTA_EXCEEDED = 'PROVIDER_SYNC_007',
  PROVIDER_SYNC_UNSUPPORTED_PROVIDER = 'PROVIDER_SYNC_008',

  // Audio preview errors (AUDIO_PREVIEW_xxx)
  AUDIO_PREVIEW_GENERATION_FAILED = 'AUDIO_PREVIEW_001',
  AUDIO_PREVIEW_FILE_NOT_FOUND = 'AUDIO_PREVIEW_002',
  AUDIO_PREVIEW_FORMAT_UNSUPPORTED = 'AUDIO_PREVIEW_003',
  AUDIO_PREVIEW_SIZE_EXCEEDED = 'AUDIO_PREVIEW_004',
  AUDIO_PREVIEW_PROCESSING_TIMEOUT = 'AUDIO_PREVIEW_005',
  AUDIO_PREVIEW_LICENSE_INVALID = 'AUDIO_PREVIEW_006',
  AUDIO_PREVIEW_QUALITY_TOO_LOW = 'AUDIO_PREVIEW_007',
  AUDIO_PREVIEW_CORRUPTED = 'AUDIO_PREVIEW_008',

  // Anonymity reveal errors (ANONYMITY_REVEAL_xxx)
  ANONYMITY_REVEAL_NOT_ALLOWED = 'ANONYMITY_REVEAL_001',
  ANONYMITY_REVEAL_CONSENT_REQUIRED = 'ANONYMITY_REVEAL_002',
  ANONYMITY_REVEAL_PREMIUM_REQUIRED = 'ANONYMITY_REVEAL_003',
  ANONYMITY_REVEAL_TIMEOUT = 'ANONYMITY_REVEAL_004',
  ANONYMITY_REVEAL_ALREADY_REVEALED = 'ANONYMITY_REVEAL_005',
  ANONYMITY_REVEAL_POLICY_VIOLATION = 'ANONYMITY_REVEAL_006',

  // Compatibility scoring errors (COMPATIBILITY_SCORING_xxx)
  COMPATIBILITY_SCORING_INSUFFICIENT_DATA = 'COMPATIBILITY_SCORING_001',
  COMPATIBILITY_SCORING_CALCULATION_FAILED = 'COMPATIBILITY_SCORING_002',
  COMPATIBILITY_SCORING_PROFILE_INCOMPLETE = 'COMPATIBILITY_SCORING_003',
  COMPATIBILITY_SCORING_ALGORITHM_ERROR = 'COMPATIBILITY_SCORING_004',
  COMPATIBILITY_SCORING_TIMEOUT = 'COMPATIBILITY_SCORING_005',
  COMPATIBILITY_SCORING_INVALID_INPUTS = 'COMPATIBILITY_SCORING_006',

  // Messaging unlock errors (MESSAGING_UNLOCK_xxx)
  MESSAGING_UNLOCK_NOT_CONNECTED = 'MESSAGING_UNLOCK_001',
  MESSAGING_UNLOCK_BLOCKED_USER = 'MESSAGING_UNLOCK_002',
  MESSAGING_UNLOCK_RATE_LIMIT = 'MESSAGING_UNLOCK_003',
  MESSAGING_UNLOCK_CONTENT_POLICY = 'MESSAGING_UNLOCK_004',
  MESSAGING_UNLOCK_MUTED = 'MESSAGING_UNLOCK_005',
  MESSAGING_UNLOCK_PREMIUM_REQUIRED = 'MESSAGING_UNLOCK_006',

  // Event participation errors (EVENT_PARTICIPATION_xxx)
  EVENT_PARTICIPATION_FULL = 'EVENT_PARTICIPATION_001',
  EVENT_PARTICIPATION_NOT_STARTED = 'EVENT_PARTICIPATION_002',
  EVENT_PARTICIPATION_ENDED = 'EVENT_PARTICIPATION_003',
  EVENT_PARTICIPATION_NOT_INVITED = 'EVENT_PARTICIPATION_004',
  EVENT_PARTICIPATION_REQUIREMENTS_NOT_MET = 'EVENT_PARTICIPATION_005',
  EVENT_PARTICIPATION_ALREADY_JOINED = 'EVENT_PARTICIPATION_006',
  EVENT_PARTICIPATION_BANNED = 'EVENT_PARTICIPATION_007',
  EVENT_PARTICIPATION_GEO_RESTRICTED = 'EVENT_PARTICIPATION_008',

  // Stellar payment errors (STELLAR_PAYMENT_xxx)
  STELLAR_PAYMENT_INSUFFICIENT_BALANCE = 'STELLAR_PAYMENT_001',
  STELLAR_PAYMENT_NETWORK_ERROR = 'STELLAR_PAYMENT_002',
  STELLAR_PAYMENT_TRANSACTION_FAILED = 'STELLAR_PAYMENT_003',
  STELLAR_PAYMENT_INVALID_DESTINATION = 'STELLAR_PAYMENT_004',
  STELLAR_PAYMENT_TIMEOUT = 'STELLAR_PAYMENT_005',
  STELLAR_PAYMENT_SEQUENCE_MISMATCH = 'STELLAR_PAYMENT_006',
  STELLAR_PAYMENT_FEE_TOO_HIGH = 'STELLAR_PAYMENT_007',
  STELLAR_PAYMENT_HORIZON_DOWN = 'STELLAR_PAYMENT_008',
  STELLAR_PAYMENT_INVALID_ASSET = 'STELLAR_PAYMENT_009',
  STELLAR_PAYMENT_TRUSTLINE_MISSING = 'STELLAR_PAYMENT_010',

  // Infrastructure errors (INFRASTRUCTURE_xxx)
  INFRASTRUCTURE_DATABASE_ERROR = 'INFRASTRUCTURE_001',
  INFRASTRUCTURE_CACHE_ERROR = 'INFRASTRUCTURE_002',
  INFRASTRUCTURE_QUEUE_ERROR = 'INFRASTRUCTURE_003',
  INFRASTRUCTURE_EXTERNAL_SERVICE_ERROR = 'INFRASTRUCTURE_004',
  INFRASTRUCTURE_RATE_LIMIT_EXCEEDED = 'INFRASTRUCTURE_005',
  INFRASTRUCTURE_MAINTENANCE_MODE = 'INFRASTRUCTURE_006',
  INFRASTRUCTURE_DISK_SPACE_FULL = 'INFRASTRUCTURE_007',
  INFRASTRUCTURE_MEMORY_LIMIT_EXCEEDED = 'INFRASTRUCTURE_008',

  // Validation errors (VALIDATION_xxx)
  VALIDATION_INVALID_INPUT = 'VALIDATION_001',
  VALIDATION_REQUIRED_FIELD_MISSING = 'VALIDATION_002',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_003',
  VALIDATION_OUT_OF_RANGE = 'VALIDATION_004',
  VALIDATION_INVALID_ENUM = 'VALIDATION_005',
  VALIDATION_DUPLICATE_VALUE = 'VALIDATION_006',
}

export interface ErrorMetadata {
  field?: string;
  value?: unknown;
  retryable?: boolean;
  userActionable?: boolean;
  context?: Record<string, unknown>;
}

export interface MixMatchError {
  code: ErrorCode;
  domain: ErrorDomain;
  message: string;
  userMessage: string;
  metadata?: ErrorMetadata;
  timestamp: string;
  requestId?: string;
}

export interface ErrorApiResponse {
  success: false;
  error: {
    code: ErrorCode;
    domain: ErrorDomain;
    message: string;
    userMessage: string;
    metadata?: ErrorMetadata;
    timestamp: string;
    requestId?: string;
  };
}

export interface ValidationErrorDetail {
  field: string;
  message: string;
  value?: unknown;
}

export interface ValidationErrorResponse {
  success: false;
  error: {
    code: ErrorCode.VALIDATION_INVALID_INPUT;
    domain: ErrorDomain.VALIDATION;
    message: string;
    userMessage: string;
    metadata: {
      validationErrors: ValidationErrorDetail[];
    };
    timestamp: string;
    requestId?: string;
  };
}

// Error severity levels
export enum ErrorSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

// Error categories for user experience
export enum ErrorCategory {
  USER_ERROR = 'USER_ERROR', // User can fix this
  SYSTEM_ERROR = 'SYSTEM_ERROR', // System issue, user cannot fix
  TEMPORARY_ERROR = 'TEMPORARY_ERROR', // Retry might work
  PERMISSION_ERROR = 'PERMISSION_ERROR', // User needs permissions
  PAYMENT_ERROR = 'PAYMENT_ERROR', // Payment related
}

// Mapping of error codes to categories
export const ERROR_CODE_CATEGORIES: Record<ErrorCode, ErrorCategory> = {
  // Auth errors
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_EMAIL_ALREADY_EXISTS]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.AUTH_TOKEN_INVALID]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_USER_NOT_FOUND]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.AUTH_ONBOARDING_INCOMPLETE]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUTH_PASSWORD_TOO_WEAK]: ErrorCategory.USER_ERROR,

  // Provider sync errors
  [ErrorCode.PROVIDER_SYNC_CONNECTION_FAILED]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.PROVIDER_SYNC_API_RATE_LIMIT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.PROVIDER_SYNC_INVALID_CREDENTIALS]: ErrorCategory.USER_ERROR,
  [ErrorCode.PROVIDER_SYNC_SERVICE_UNAVAILABLE]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.PROVIDER_SYNC_DATA_MALFORMED]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.PROVIDER_SYNC_TIMEOUT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.PROVIDER_SYNC_QUOTA_EXCEEDED]: ErrorCategory.USER_ERROR,
  [ErrorCode.PROVIDER_SYNC_UNSUPPORTED_PROVIDER]: ErrorCategory.USER_ERROR,

  // Audio preview errors
  [ErrorCode.AUDIO_PREVIEW_GENERATION_FAILED]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.AUDIO_PREVIEW_FILE_NOT_FOUND]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.AUDIO_PREVIEW_FORMAT_UNSUPPORTED]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUDIO_PREVIEW_SIZE_EXCEEDED]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUDIO_PREVIEW_PROCESSING_TIMEOUT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.AUDIO_PREVIEW_LICENSE_INVALID]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUDIO_PREVIEW_QUALITY_TOO_LOW]: ErrorCategory.USER_ERROR,
  [ErrorCode.AUDIO_PREVIEW_CORRUPTED]: ErrorCategory.SYSTEM_ERROR,

  // Anonymity reveal errors
  [ErrorCode.ANONYMITY_REVEAL_NOT_ALLOWED]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.ANONYMITY_REVEAL_CONSENT_REQUIRED]: ErrorCategory.USER_ERROR,
  [ErrorCode.ANONYMITY_REVEAL_PREMIUM_REQUIRED]: ErrorCategory.PAYMENT_ERROR,
  [ErrorCode.ANONYMITY_REVEAL_TIMEOUT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.ANONYMITY_REVEAL_ALREADY_REVEALED]: ErrorCategory.USER_ERROR,
  [ErrorCode.ANONYMITY_REVEAL_POLICY_VIOLATION]: ErrorCategory.PERMISSION_ERROR,

  // Compatibility scoring errors
  [ErrorCode.COMPATIBILITY_SCORING_INSUFFICIENT_DATA]: ErrorCategory.USER_ERROR,
  [ErrorCode.COMPATIBILITY_SCORING_CALCULATION_FAILED]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.COMPATIBILITY_SCORING_PROFILE_INCOMPLETE]: ErrorCategory.USER_ERROR,
  [ErrorCode.COMPATIBILITY_SCORING_ALGORITHM_ERROR]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.COMPATIBILITY_SCORING_TIMEOUT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.COMPATIBILITY_SCORING_INVALID_INPUTS]: ErrorCategory.USER_ERROR,

  // Messaging unlock errors
  [ErrorCode.MESSAGING_UNLOCK_NOT_CONNECTED]: ErrorCategory.USER_ERROR,
  [ErrorCode.MESSAGING_UNLOCK_BLOCKED_USER]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.MESSAGING_UNLOCK_RATE_LIMIT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.MESSAGING_UNLOCK_CONTENT_POLICY]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.MESSAGING_UNLOCK_MUTED]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.MESSAGING_UNLOCK_PREMIUM_REQUIRED]: ErrorCategory.PAYMENT_ERROR,

  // Event participation errors
  [ErrorCode.EVENT_PARTICIPATION_FULL]: ErrorCategory.USER_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_NOT_STARTED]: ErrorCategory.USER_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_ENDED]: ErrorCategory.USER_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_NOT_INVITED]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_REQUIREMENTS_NOT_MET]: ErrorCategory.USER_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_ALREADY_JOINED]: ErrorCategory.USER_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_BANNED]: ErrorCategory.PERMISSION_ERROR,
  [ErrorCode.EVENT_PARTICIPATION_GEO_RESTRICTED]: ErrorCategory.PERMISSION_ERROR,

  // Stellar payment errors
  [ErrorCode.STELLAR_PAYMENT_INSUFFICIENT_BALANCE]: ErrorCategory.PAYMENT_ERROR,
  [ErrorCode.STELLAR_PAYMENT_NETWORK_ERROR]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.STELLAR_PAYMENT_TRANSACTION_FAILED]: ErrorCategory.PAYMENT_ERROR,
  [ErrorCode.STELLAR_PAYMENT_INVALID_DESTINATION]: ErrorCategory.USER_ERROR,
  [ErrorCode.STELLAR_PAYMENT_TIMEOUT]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.STELLAR_PAYMENT_SEQUENCE_MISMATCH]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.STELLAR_PAYMENT_FEE_TOO_HIGH]: ErrorCategory.PAYMENT_ERROR,
  [ErrorCode.STELLAR_PAYMENT_HORIZON_DOWN]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.STELLAR_PAYMENT_INVALID_ASSET]: ErrorCategory.USER_ERROR,
  [ErrorCode.STELLAR_PAYMENT_TRUSTLINE_MISSING]: ErrorCategory.PAYMENT_ERROR,

  // Infrastructure errors
  [ErrorCode.INFRASTRUCTURE_DATABASE_ERROR]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.INFRASTRUCTURE_CACHE_ERROR]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.INFRASTRUCTURE_QUEUE_ERROR]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.INFRASTRUCTURE_EXTERNAL_SERVICE_ERROR]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.INFRASTRUCTURE_RATE_LIMIT_EXCEEDED]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.INFRASTRUCTURE_MAINTENANCE_MODE]: ErrorCategory.TEMPORARY_ERROR,
  [ErrorCode.INFRASTRUCTURE_DISK_SPACE_FULL]: ErrorCategory.SYSTEM_ERROR,
  [ErrorCode.INFRASTRUCTURE_MEMORY_LIMIT_EXCEEDED]: ErrorCategory.SYSTEM_ERROR,

  // Validation errors
  [ErrorCode.VALIDATION_INVALID_INPUT]: ErrorCategory.USER_ERROR,
  [ErrorCode.VALIDATION_REQUIRED_FIELD_MISSING]: ErrorCategory.USER_ERROR,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: ErrorCategory.USER_ERROR,
  [ErrorCode.VALIDATION_OUT_OF_RANGE]: ErrorCategory.USER_ERROR,
  [ErrorCode.VALIDATION_INVALID_ENUM]: ErrorCategory.USER_ERROR,
  [ErrorCode.VALIDATION_DUPLICATE_VALUE]: ErrorCategory.USER_ERROR,
} as const;
